# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlGuard < Formula
  desc "Kubernetes context protection kubectl plugin"
  homepage "https://github.com/sivchari/kubectl-guard"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_darwin_amd64.tar.gz"
      sha256 "b8411d1950b3b3f8bad0ca0484407e77a50e150ecdc91274fed034d215873aca"

      def install
        bin.install "kubectl-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_darwin_arm64.tar.gz"
      sha256 "224fe440e9c57bb2f51121acd353de7c832a9821c00597e04000fc44ab16c754"

      def install
        bin.install "kubectl-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_linux_amd64.tar.gz"
      sha256 "3b0f23fc667be88099ad088c9551d5c1cd462bc26d3648d9dd56ca809d6755b6"
      def install
        bin.install "kubectl-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_linux_arm64.tar.gz"
      sha256 "9378f2e4f751a8cfe8b06a86f4a8db26deb5db138a989cbe1e012e4ea4d0d80c"
      def install
        bin.install "kubectl-guard"
      end
    end
  end
end
