# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlGuard < Formula
  desc "Kubernetes context protection kubectl plugin"
  homepage "https://github.com/sivchari/kubectl-guard"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_darwin_amd64.tar.gz"
      sha256 "8dc7c3ee38b357641f1face6deb79331aba68960644f0f420ae408d5fb325ea3"

      def install
        bin.install "kubectl-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_darwin_arm64.tar.gz"
      sha256 "ae6562eef382581529f54e654bf2a0b087855f387b7e58a5006117825a9bc730"

      def install
        bin.install "kubectl-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_linux_amd64.tar.gz"
      sha256 "893ff966fdec45e6e57c05ae6fae7810fc1d6f4f12227d23a7fbefcf01037d0e"
      def install
        bin.install "kubectl-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sivchari/kubectl-guard/releases/download/v0.0.2/kubectl-guard_0.0.2_linux_arm64.tar.gz"
      sha256 "96574a1cb8120c7fc649d40dc1661b4b0b4a196af1a32932f43495f747fc7114"
      def install
        bin.install "kubectl-guard"
      end
    end
  end
end
