# This file was generated by GoReleaser. DO NOT EDIT.
cask "crx" do
  name "crx"
  desc "Declarative Chrome extension manager using Chrome Enterprise Policy"
  homepage "https://github.com/sivchari/crx"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crx"

  on_macos do
    on_intel do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_darwin_amd64.tar.gz"
      sha256 "1028e4faee1e3d926d6da10ee662ed22a2078cda533a9c07c27290969cf7248c"
    end
    on_arm do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_darwin_arm64.tar.gz"
      sha256 "b6a61343fb9e0665eac62bc87dcab4c122b7069fffbaf1c02c149be7b6fae622"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_linux_amd64.tar.gz"
      sha256 "dcc1b54ac65ab26c1317a216da9c8bd3d5f44f7bee5068490ccc5e16cf64296b"
    end
    on_arm do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_linux_arm64.tar.gz"
      sha256 "985c87a77bd4a9cedd90c0abc606fc6fd9675554aaf776a16e1e0d84a53006ef"
    end
  end

  # No zap stanza required
end
