# This file was generated by GoReleaser. DO NOT EDIT.
cask "crx" do
  name "crx"
  desc "Declarative Chrome extension manager using Chrome Enterprise Policy"
  homepage "https://github.com/sivchari/crx"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crx"

  on_macos do
    on_intel do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_darwin_amd64.tar.gz"
      sha256 "94445ee14e0e4e35ae57483c8fb8ecd2f97106e7711a10e4292bbe398d41bc37"
    end
    on_arm do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_darwin_arm64.tar.gz"
      sha256 "8014bc38f50093a096ef9ff953824b946353488686f80489bf0758b0e5e8f3b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_linux_amd64.tar.gz"
      sha256 "f89a7c27c1204f07b2623a81f3498c736b109b4d180d7da2ea7d3e003197a9da"
    end
    on_arm do
      url "https://github.com/sivchari/crx/releases/download/v#{version}/crx_#{version}_linux_arm64.tar.gz"
      sha256 "bd010d7fdb94b7d54a5fa2c6d27527f7927adf91d9cf9ef0f0cbfea55210d327"
    end
  end

  # No zap stanza required
end
