# This file was generated by GoReleaser. DO NOT EDIT.
cask "gomu" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "db7351e87920c963a4c857999f47d7af8ff949fcfe527d8ce2143afe88c06aa8"
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b417c1c153460e70480084be7baa85d8abfc313d58049e1df2aa24c4f3e7a2f2"
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5464567ad83ab52b622e8ef7e7fc7c3c4896a97ecaaf5455070fcbb333ca8483"
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc3dedd11f467c1ab19e2a027fd8d166b4f0011bbb5426fe776f9cb7736f4a02"
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gomu"
  desc "A high-performance mutation testing tool for Go"
  homepage "https://github.com/sivchari/gomu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gomu"

  # No zap stanza required

end
