# This file was generated by GoReleaser. DO NOT EDIT.
cask "gomu" do
  name "gomu"
  desc "A high-performance mutation testing tool for Go"
  homepage "https://github.com/sivchari/gomu"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gomu"

  on_macos do
    on_intel do
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_darwin_amd64.tar.gz"
      sha256 "d9e6a471630ce1d01b6b683c2cb4aa9f72ab41ef1234443020c3885cf71f0cd8"
    end
    on_arm do
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_darwin_arm64.tar.gz"
      sha256 "80ed95f9ee59a819077aad70b9cd42aaebaa850430e895f84b8e86933cf91acf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_linux_amd64.tar.gz"
      sha256 "37400c93f2c9fcaddb49d43dca54636729642e92afaa5f733d86cd7c7f435451"
    end
    on_arm do
      url "https://github.com/sivchari/gomu/releases/download/v#{version}/gomu_#{version}_linux_arm64.tar.gz"
      sha256 "89bffc23be4106e230ef0a7ad7ec026f8915b83802d0d1d75b0450063cc93637"
    end
  end

  # No zap stanza required
end
