# This file was generated by GoReleaser. DO NOT EDIT.
cask "govalid" do
  desc "A Go code generator for validation functions"
  homepage "https://github.com/sivchari/govalid"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govalid"

  on_macos do
    on_intel do
      url "https://github.com/sivchari/govalid/releases/download/v1.1.0/govalid_1.1.0_darwin_amd64.tar.gz"
      sha256 "922e4b4fa7a23687c7c326d8613f17d28a475816d8d26668769bf18b45717c20"
    end
    on_arm do
      url "https://github.com/sivchari/govalid/releases/download/v1.1.0/govalid_1.1.0_darwin_arm64.tar.gz"
      sha256 "99df7e211f42365da66584ad4126aa59e08c1d8560c1bd0be41c91dc2d70d9b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sivchari/govalid/releases/download/v1.1.0/govalid_1.1.0_linux_amd64.tar.gz"
      sha256 "dc0a4104f245c79cc39e6e009e21a997747a825a3553f9be73e1d5e84fc39ee0"
    end
    on_arm do
      url "https://github.com/sivchari/govalid/releases/download/v1.1.0/govalid_1.1.0_linux_arm64.tar.gz"
      sha256 "5966ef6c82fa056f064a1f09a04e9d5889281206e60be265cd392c5aea02d9fa"
    end
  end

  conflicts_with formula: [
      "govalid",
    ]

  # No zap stanza required
end
