# This file was generated by GoReleaser. DO NOT EDIT.
cask "govalid" do
  name "govalid"
  desc "A Go code generator for validation functions"
  homepage "https://github.com/sivchari/govalid"
  version "1.7.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govalid"

  on_macos do
    on_intel do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_darwin_amd64.tar.gz"
      sha256 "5d9b3b47d317eed505f4db5efaaa98356dfdeeb9007f2346fe2ed5390e10033a"
    end
    on_arm do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_darwin_arm64.tar.gz"
      sha256 "b6ab10b4628b861ea92f1ab4d56498f80cd4068ad00c8f1b65f5df94c2d45e1e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_linux_amd64.tar.gz"
      sha256 "655e85d90cc5e44fbff3239a496e342b38e5694f308dbbb644228b8f90559fd2"
    end
    on_arm do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_linux_arm64.tar.gz"
      sha256 "f4649118b9019b530618dfa463e93f87fd5a8afc06dac36a9a683976102cb572"
    end
  end

  # No zap stanza required
end
