# This file was generated by GoReleaser. DO NOT EDIT.
cask "govalid" do
  name "govalid"
  desc "A Go code generator for validation functions"
  homepage "https://github.com/sivchari/govalid"
  version "1.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "govalid"

  on_macos do
    on_intel do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_darwin_amd64.tar.gz"
      sha256 "03fec93cc79a4ab88446dfab543905673eac3495ddd28321bd8d251879cb2618"
    end
    on_arm do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_darwin_arm64.tar.gz"
      sha256 "75f0325e53d19c6709df9c22aa205cfb1226469fbbaea80f6fe882376e220595"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_linux_amd64.tar.gz"
      sha256 "0aa54a9d8a89b409056ce12854c4e4b8918fc39bfcdf4c75178ac6f9e34df490"
    end
    on_arm do
      url "https://github.com/sivchari/govalid/releases/download/v#{version}/govalid_#{version}_linux_arm64.tar.gz"
      sha256 "765f3684621df82dd0a8affec2dee1cb433d80e7f87c7a2e2a648c0c6b82f329"
    end
  end

  # No zap stanza required
end
