# This file was generated by GoReleaser. DO NOT EDIT.
cask "kumo" do
  version "0.28.0"

  on_macos do
    on_intel do
      sha256 "31d46ecbb6a58ebf131ca56ee6b529c46d5b123ae84ebb445cf86201f0b42e8b"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec56460c32acbbb4026e776c291a65fa63a1e433f48d348088ad496af57be095"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "154705f9388a7a18a4c7511a42029e6652b81abde1cc450b59d4d9ccab2f4e16"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8dacf1d00838965a9b2f5b71138468c36451f7cd43796965af54f4f598cef54"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kumo"
  desc "A lightweight AWS service emulator for CI/CD environments"
  homepage "https://github.com/sivchari/kumo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kumo"

  # No zap stanza required

end
