# This file was generated by GoReleaser. DO NOT EDIT.
cask "kumo" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "1857290327288f87b8f9bf3786da30e3e9c6e64781fab24ea9262bf07d02038f"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d5aa2f37d634b2aeaec3ed044b6624029e4f66c9996d37524eca95195644532c"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0fa19fd6316292b6cf49d674913dbeeca3e4d7541a00a5f2c3634134e71c621a"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "07609ecffb6a727f1d3c2ce540ca466eaeed4f321ac28fd6f78cff6632db7b0f"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kumo"
  desc "A lightweight AWS service emulator for CI/CD environments"
  homepage "https://github.com/sivchari/kumo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kumo"

  # No zap stanza required

end
