# This file was generated by GoReleaser. DO NOT EDIT.
cask "kumo" do
  version "0.18.1"

  on_macos do
    on_intel do
      sha256 "d02ed7cfbaac743f9669944bca833410a8510872e5819161851af257201b5629"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "81c3d345b9cea5b5cdca833990882bdf6f95c451847a959544adaf2122850472"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7025b7c91f1604ab91c0133bccb187a8bf651228a618dfe637ab756eaa2a6447"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "754a321a4e50b06cc8cd25fe69f17ceb57c1491910b527fd6a5bc926a55a9337"
      url "https://github.com/sivchari/kumo/releases/download/v#{version}/kumo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kumo"
  desc "A lightweight AWS service emulator for CI/CD environments"
  homepage "https://github.com/sivchari/kumo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kumo"

  # No zap stanza required

end
